export type CityUser = {
    ref: any,
    blocked: any,
    verified: any,
    rating1: number | null,
    rating2: number | null,
    rating3: number | null,
    rating4: number | null,
    rating5: number | null,
    locations: boolean | null,
    someBoolean: boolean | null,
    name: string | null,
    phone: string | null,
    photoUrl: string | null,
    countryCode: string | null,
    lastAppRateDate: undefined,
    dateRegistration: undefined,
    tokens: [string] | null,
}
